### ISSUE TITLE
Idea: worcs badge

### ISSUE THREAD

**Issue by brandmaier** [cjvanlissa/worcs#19]
How about a worcs badge that is automatically integrated into the readme.md, so that it is shown in worcs projects on github.

For example, shields.io can be used to generate simply badges, like this:
https://img.shields.io/badge/worcs-compatible-557788?style=plastic&color=2E70B9
which becomes:
<img width="114" src="https://img.shields.io/badge/worcs-compatible-557788?style=plastic&color=2E70B9">
Or, let's create a fancy badge with the logo...

Further, we could habe a function validate() that tests whether a given directory is a valid worcs repository (e.g., by checking whether it has a .worcs file and whether all checksums match). Then, Readme.md could have a placeholder tag that is replaced by a validate()-call either with the worcs badge or by a "incompatible" badge.

**Comment by cjvanlissa** [comment]
Resolved by 80b9d12872452a85aac7a36ec282220eed02a1c9

**Comment by cjvanlissa** [comment]
As README.md is not dynamically generated, I leave it to the user when they want to validate their project. They can validate the worcs project directory, which creates a checklist.csv. This can be manually updated for "bonus" points that cannot be automatically checked. After manually updating, they can also validate the checklist.csv instead of the directory.
