### ISSUE TITLE
git_push() can't find credentials when called from git_update()

### ISSUE THREAD

**Issue by cjvanlissa** [cjvanlissa/worcs#31]
Feedback requested.

I would like to have this function to do a "quick save" to github! Even if only for my own use. But I get an error in the git_push() call.

bd2f25bccdc6228c07302189bf71b8430d6899f3

**Comment by aaronpeikert** [comment]
Something like that I had in mind when I was talking about freeing the user from using git. Some facilities that automate git at the cost of turning it from explicit version control to implicit version control.
So I like the idea a lot (ok not really; people should use git, but what are we to do with those who refuse to be enlightened, spare them the wonders of reproducibility all together? :angel: ).
However, I would suggest waiting a little bit with this feature because not only do I want to think about the mental model of this but also about the implementation. Do you think it is necessary for the cran release?

**Comment by cjvanlissa** [comment]
Not necessary. But I would personally use it a lot :)

**Comment by aaronpeikert** [comment]
This is a good implementation, but I fear it is not all too robust (I quick analysis of use cases shows that this particular implementation depends strongly on the git setup and particular state of git) at the moment I don't want to go down that rabbit hole.

**Comment by aaronpeikert** [comment]
You shouldn't :smiling_imp: , but I have to agree it is tempting...

**Comment by cjvanlissa** [comment]
I'll send a pull request to gert to see if Jeroen wants to incorporate both git_ functions

**Comment by aaronpeikert** [comment]
That would be great.
